/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VENTAS;

import UsuariosAdmin.usuario;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import proyectodesarrollo.AdministrarProductos;
import proyectodesarrollo.Proveedores;

/**
 *
 * @author Daysi
 */
public class MenuVentas extends javax.swing.JFrame {

    int ejex;
    int ejey;

    /**
     * Creates new form MenuVentas
     */
    public MenuVentas() {
        initComponents();
        lblCajero.setVisible(false);
        //this.setExtendedState(MenuVentas.MAXIMIZED_BOTH);
         //setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());         
    }

//    public MenuVentas(String dato) {
//        initComponents();
//        lblCajero.setText(dato);
//    }

//    public void pasarSeleccion() {
//        String var2 = lblCajero.getText();
//        ventas.cajeros(var2);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lblCajero = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuInicio = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuEmpleados = new javax.swing.JMenu();
        AdminProductos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        ItemVentas = new javax.swing.JMenu();
        Ventas = new javax.swing.JMenuItem();
        MenuConsultas = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCajero.setToolTipText("");

        escritorio.setLayer(lblCajero, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1150, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(584, Short.MAX_VALUE))
        );

        MenuInicio.setText("Archivo");
        MenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInicioActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.png"))); // NOI18N
        jMenuItem1.setText("Cerrar Sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuInicio.add(jMenuItem1);

        jMenuBar1.add(MenuInicio);

        MenuEmpleados.setText("Usuarios");
        MenuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmpleadosActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuEmpleados);

        AdminProductos.setText("Compras");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compra.png"))); // NOI18N
        jMenuItem2.setText("Administrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        AdminProductos.add(jMenuItem2);

        jMenuBar1.add(AdminProductos);

        ItemVentas.setText("Ventas");

        Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.png"))); // NOI18N
        Ventas.setText("Abrir");
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });
        ItemVentas.add(Ventas);

        jMenuBar1.add(ItemVentas);

        MenuConsultas.setText("Consultas");
        MenuConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuConsultasMouseClicked(evt);
            }
        });
        MenuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsultasActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuConsultas);

        jMenu1.setText("Proveedores");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedor.png"))); // NOI18N
        jMenuItem3.setText("Administrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuInicioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
        try {
            ventas ap = new ventas();
            ejex = (escritorio.getWidth() / 2) - (ap.getWidth() / 2);
            ejey = (escritorio.getHeight() / 2) - (ap.getHeight() / 2) + 20;
            escritorio.removeAll();
            escritorio.add(ap);
            ap.setLocation(ejex, ejey);
            ap.show();
        } catch (Exception ex) {
            //Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_VentasActionPerformed
    PanelVistaFactura Facturas = new PanelVistaFactura();
    private void MenuConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuConsultasMouseClicked
        if (Facturas.isShowing()) {
            JOptionPane.showMessageDialog(null, "Ventana activa");
        } else {
            Facturas.add(escritorio);
            Facturas.show();
            Dimension desktopSize = escritorio.getSize();
            Dimension FrameSize = Facturas.getSize();
            Facturas.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        }
    }//GEN-LAST:event_MenuConsultasMouseClicked
    Proveedores n = new Proveedores();
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        if (n.isShowing()) {
            JOptionPane.showMessageDialog(null, "Ventana activa");
        } else {
            n.add(escritorio);
            n.show();
            Dimension desktopSize = escritorio.getSize();
            Dimension FrameSize = n.getSize();
            n.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       try {
            AdministrarProductos ap = new AdministrarProductos();
            ejex = (escritorio.getWidth() / 2) - (ap.getWidth() / 2);
            ejey = (escritorio.getHeight() / 2) - (ap.getHeight() / 2) + 20;
            escritorio.removeAll();
            escritorio.add(ap);
            ap.setLocation(ejex, ejey);
            ap.show();
        } catch (Exception ex) {
            //Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MenuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmpleadosActionPerformed
        try {
            usuario ap = new usuario();
            ejex = (escritorio.getWidth() / 2) - (ap.getWidth() / 2);
            ejey = (escritorio.getHeight() / 2) - (ap.getHeight() / 2) + 20;
            escritorio.removeAll();
            escritorio.add(ap);
            ap.setLocation(ejex, ejey);
            ap.show();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_MenuEmpleadosActionPerformed

    private void MenuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsultasActionPerformed
 try {
            PanelVistaFactura ap = new PanelVistaFactura();
            ejex = (escritorio.getWidth() / 2) - (ap.getWidth() / 2);
            ejey = (escritorio.getHeight() / 2) - (ap.getHeight() / 2) + 20;
            escritorio.removeAll();
            escritorio.add(ap);
            ap.setLocation(ejex, ejey);
            ap.show();
        } catch (Exception ex) {
            //Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MenuConsultasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
try {
            Proveedores ap = new Proveedores();
            ejex = (escritorio.getWidth() / 2) - (ap.getWidth() / 2);
            ejey = (escritorio.getHeight() / 2) - (ap.getHeight() / 2) + 20;
            escritorio.removeAll();
            escritorio.add(ap);
            ap.setLocation(ejex, ejey);
            ap.show();
        } catch (Exception ex) {
            //Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu AdminProductos;
    public javax.swing.JMenu ItemVentas;
    public javax.swing.JMenu MenuConsultas;
    public javax.swing.JMenu MenuEmpleados;
    public javax.swing.JMenu MenuInicio;
    private javax.swing.JMenuItem Ventas;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JLabel lblCajero;
    // End of variables declaration//GEN-END:variables
}
